-- 				nls.builtins.formatting.prettier.with {
-- 					filetypes = {
-- 						'css',
-- 						'graphql',
-- 						'html',
-- 						'javascript',
-- 						'javascriptreact',
-- 						'json',
-- 						'less',
-- 						'markdown',
-- 						'scss',
-- 						'typescript',
-- 						'typescriptreact',
-- 						'yaml',
-- 					},
-- 					timeout = 5000,
-- 				},
-- 				nls.builtins.formatting.stylua,
-- 				nls.builtins.formatting.clang_format,
-- 				nls.builtins.formatting.black,
-- 				nls.builtins.formatting.isort,
-- 				nls.builtins.formatting.rustfmt,

return {
	-- {
	-- 	'mhartington/formatter.nvim',
	-- 	config = function()
	-- 		local fmt = require 'formatter.filetypes'

	-- 		require 'formatter'.setup {
	-- 			-- Enable or disable logging
	-- 			logging = false,

	-- 			-- All formatter configurations are opt-in
	-- 			filetype = {
	-- 				-- Formatter configurations for filetype "lua" go here
	-- 				-- and will be executed in order
	-- 				css = { fmt.prettier },
	-- 				graphql = { fmt.prettier },
	-- 				html = { fmt.prettier },
	-- 				javascript = { fmt.prettier },
	-- 				javascriptreact = { fmt.prettier },
	-- 				json = { fmt.prettier },
	-- 				less = { fmt.prettier },
	-- 				markdown = { fmt.prettier },
	-- 				scss = { fmt.prettier },
	-- 				typescript = { fmt.prettier },
	-- 				typescriptreact = { fmt.prettier },
	-- 				yaml = { fmt.prettier },
	-- 				lua = {},

	-- 				-- Use the special "*" filetype for defining formatter configurations on
	-- 				-- any filetype
	-- 				["*"] = {
	-- 					-- "formatter.filetypes.any" defines default configurations for any
	-- 					-- filetype
	-- 					require("formatter.filetypes.any").remove_trailing_whitespace
	-- 				}
	-- 			}
	-- 		}
	-- 	end
	-- }
}
